name: Build and Push Spack Container

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Spack
        run: |
          git clone --depth 1 --branch v0.23.0 https://github.com/spack/spack.git
          echo "${GITHUB_WORKSPACE}/spack/bin" >> $GITHUB_PATH

      - name: Generate Dockerfile with Spack
        run: |
          cd spack-env
          ../spack/bin/spack containerize > Dockerfile

      - name: Upload generated Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: spack-dockerfile
          path: spack-env/Dockerfile

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./spack-env/
          push: true
          tags: ghcr.io/${{ github.repository }}/spack-env:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
